# Generated by Django 5.2.6 on 2025-09-15 12:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendee',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['row', 'seat_number']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='seat',
            name='is_occupied',
        ),
        migrations.AddField(
            model_name='attendee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='Event description', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is event active/visible'),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, help_text='Event start time', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Is seat available for booking'),
        ),
        migrations.AddField(
            model_name='section',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text='Total seats in section'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='seat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendee', to='seating.seat'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(help_text='Event date'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='seating.section'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='x_coordinate',
            field=models.FloatField(help_text='X position on seat map (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='seat',
            name='y_coordinate',
            field=models.FloatField(help_text='Y position on seat map (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='section',
            name='color',
            field=models.CharField(default='#3498db', help_text='Hex color for map', max_length=7),
        ),
        migrations.AlterField(
            model_name='section',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='seating.event'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('event', 'name')},
        ),
        migrations.AddIndex(
            model_name='attendee',
            index=models.Index(fields=['ticket_number'], name='seating_att_ticket__08c63b_idx'),
        ),
        migrations.AddIndex(
            model_name='attendee',
            index=models.Index(fields=['email'], name='seating_att_email_cb8ed7_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date'], name='seating_eve_date_26d84e_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_active'], name='seating_eve_is_acti_53133f_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['section', 'is_available'], name='seating_sea_section_b55ae0_idx'),
        ),
    ]
